version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ../wordpress/site:/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        resources:
            limits:
                cpus: '0.2'
                memory: 256M
            reservations:
                cpus: '0.2'
                memory: 128M
    php:
        build: 
            context: .
            dockerfile: dockerfile-php7fpm-mysqli
        volumes:
            - ../wordpress/site:/www
        networks:
            - code-network
        resources:
            limits:
                cpus: '0.2'
                memory: 256M
            reservations:
                cpus: '0.2'
                memory: 128M

networks:
    code-network:
        driver: bridge
