version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ../wordpress/site:/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: 
            context: .
            dockerfile: dockerfile-php7fpm-mysqli
        volumes:
            - ../wordpress/site:/www
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
