version: '2'

services:
    web:
        image: 379709885387.dkr.ecr.us-west-2.amazonaws.com/inpa-nginx:latest
        ports:
            - "80:80"
        networks:
            - code-network
        cpu_shares: 100
        mem_limit: 128000000

    php:
        image: 379709885387.dkr.ecr.us-west-2.amazonaws.com/inpa-wp:latest 
        networks:
            - code-network
        cpu_shares: 100
        mem_limit: 256000000

networks:
    code-network:
        driver: bridge
